# Generated by Django 2.2.28 on 2022-12-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20221213_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245, unique=True)),
                ('position', models.CharField(max_length=245, unique=True)),
                ('photo', models.ImageField(upload_to='students/')),
                ('discription', models.TextField()),
            ],
        ),
    ]
