# Generated by Django 2.2.28 on 2022-12-17 07:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
